### ISSUE TITLE
End my life or Add Re(try to)encode

### ISSUE THREAD

**Issue by Zenkyou** [Franiac/TwitchLeecher#133]
This is a suggestion/request:
I was downloadinng a big broadcast and everything was fine until the enconde process while give me an error http://i.imgur.com/441recD.png 
Will be pretty nice if we can have a function to try do enconde again
Other thant this the App work very well. Thank you very musch

-
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 137667481
Selected Quality: 1280x720@27fps
Download Url: https://www.twitch.tv/videos/137667481
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Pessoa\Downloads\20170423_137667481_PLAYERUNKNOWN'S BATTLEGROUNDS.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Pessoa\AppData\Local\Temp\TL_7b1538b4-6ba4-4e95-9a61-63ffdeb79935

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A137667481%2C%22expires%22%3A1493493971%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: b2b1393e3c6f3581a094183e97c91c753b4e4b5f
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Pessoa\AppData\Local\Temp\TL_7b1538b4-6ba4-4e95-9a61-63ffdeb79935'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-dvr.m3u8
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/audio_only/index-dvr.m3u8
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/720p30/index-dvr.m3u8
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/480p30/index-dvr.m3u8
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/360p30/index-dvr.m3u8
https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@27fps is https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 8985

Starting parallel video chunk download
Number of video chunks to download: 8985
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000001169-nC44.ts?start_offset=15590840&end_offset=16902139' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000003149-aBx6.ts?start_offset=21385188&end_offset=22682387' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000002159-NURv.ts?start_offset=35581444&end_offset=36884847' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000005159-ruEA.ts?start_offset=2423508&end_offset=3821475' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000006149-gtKH.ts?start_offset=20573780&end_offset=21856879' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod055-ttvnw.akamaized.net/v1/AUTH_system/vods_fedd/patri0ta_25123278688_638875413/chunked/index-0000001169-nC44.ts?start_offset=15590840&end_offset=16902139' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Pessoa\AppData\Local\Temp\TL_7b1538b4-6ba4-4e95-9a61-63ffdeb79935\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\Pessoa\AppData\Local\Temp\TL_7b1538b4-6ba4-4e95-9a61-63ffdeb79935\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Pessoa\Downloads\20170423_137667481_PLAYERUNKNOWN'S BATTLEGROUNDS.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Pessoa\AppData\Local\Temp\TL_7b1538b4-6ba4-4e95-9a61-63ffdeb79935'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
TL does not encode anything, TL downloads and merges.ts files with ffmpeg, that's all. Retrying is pointless because if the source stream has an error that prevents ffmpeg from merging you will get the same error over and over. TL can only merge VODs that are error-free. If the streamer has bad internet connection or drops a lot of frames, ffmpeg can run into errors that it cannot handle. That's something I cannot change even with black magic...
