### ISSUE TITLE
Option to prevent temp deletion and restart encoder

### ISSUE THREAD

**Issue by fireundubh** [Franiac/TwitchLeecher#135]
I just encountered an exception during encode, but the only way to restart the encoder is to redownload the broadcast again. An option to keep the temp files and restart the encoder would be nice.

```
Starting temporary download folder cleanup!
Deleting directory 'D:\temp\TL_a5e95aeb-cefd-430a-96a5-94dceb061bfc'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---```

**Comment by Franiac** [comment]
TL does not encode anything. I should definitely re-phrase the error message. TL only merges VOD parts together with ffmpeg, nothing more. If this process fails, the source VOD/stream contains a problem that ffmpeg cannot fix. there is no point to re-download such a VOD. If the process fails once, it will fail everytime. The streamer probably dropped frames, had a bad internet connection or something else. TL cannot fix errors that occured during the stream, it also does not re-encode the stream.

**Comment by fireundubh** [comment]
>  TL only merges VOD parts together with ffmpeg, nothing more. 

Yes, but you also run `TwitchLeecher.Services.Services.TwitchService.CleanUp` which deletes the VOD parts. If ffmpeg throws an error, it is not possible to try merging again without redownloading the VOD.

> there is no point to re-download such a VOD. If the process fails once, it will fail everytime.

In this case, I had run out of disk space. The merged VOD would have been 13-14 GB. I freed up some space, redownloaded the VOD, and the merge completed successfully.
