### ISSUE TITLE
99% then error

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#161]
I've noticed several times downloads get to 99% then error after a while. Redownloading works.

Does this error report help you see if there's an identifiable issue?

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.9

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 140327397
Selected Quality: 852x480@30fps
Download Url: https://www.twitch.tv/videos/140327397
Crop Start: Yes (00:19:55)
Crop End: Yes (04:38:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Downloaded1\WhatCD5\oBby190_20170505_140327397b 20-438 The Filthiest of Casuals - Duo Competitive [Diamond Mercy Main]_Overwatch.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\K\AppData\Local\Temp\1TwLch\TL_859536c0-9844-4729-a1a8-eb45ab3401ea

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A140327397%2C%22expires%22%3A1499250519%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: aeefd2f1d7c40d3674bedb5259b073063b11de14
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_859536c0-9844-4729-a1a8-eb45ab3401ea'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/chunked/index-muted-E4X44R7UDV.m3u8
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/audio_only/index-muted-E4X44R7UDV.m3u8
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/720p60/index-muted-E4X44R7UDV.m3u8
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-muted-E4X44R7UDV.m3u8
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/360p30/index-muted-E4X44R7UDV.m3u8
https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/160p30/index-muted-E4X44R7UDV.m3u8

Playlist url for selected quality 852x480@30fps is https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-muted-E4X44R7UDV.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 11542

Starting parallel video chunk download
Number of video chunks to download: 7923
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000006779-UkLS-1349464.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000001469-jk2q-6701260.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000008489-T29M-7434460.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000006779-UkLS-1349464.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000001469-jk2q-6701260.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000008489-T29M-7434460.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000006779-UkLS-1349464.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000001469-jk2q-6701260.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000008489-T29M-7434460.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_859536c0-9844-4729-a1a8-eb45ab3401ea'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000005849-RzeQ-9152216.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---

---> (Inner Exception #1) System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000006779-UkLS-1349464.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---

---> (Inner Exception #2) System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000001469-jk2q-6701260.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---

---> (Inner Exception #3) System.ApplicationException: Could not download file 'https://vod-metro.twitch.tv/ab9142bd43_obby190_25210692944_644338804/480p30/index-0000008489-T29M-7434460.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass62_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---
<---

**Comment by Franiac** [comment]
It's the same issue you posted with #98 
Your internet connection seems really really bad at times. You see that TL often tried to download multiple VOD parts up to 3 times. But if TL does not get a part after the 3rd retry, it gives up.

**Comment by tezJR** [comment]
Is there any indication of why it stopped downloading at 99% though? Or is that simply an artefact of it downloading everything except the few parts it failed on?

**Comment by Franiac** [comment]
There were 7923 parts to download. If TL failed on 99%, it must have been one of the later parts that failed. There is no specific reason why it hit you at exactly 99%. Could also have been 43%. But consider also the fact that TL downloads 10 parts in parallel. So just because TL waits 20s 3 times in a row for a part that failed, does not mean it stops downloading.
