### ISSUE TITLE
Error on Url and ID searching

### ISSUE THREAD

**Issue by ifusayso** [Franiac/TwitchLeecher#176]
Since this morning I've been getting this error when trying to perform a search using the video ID or Url search boxes.  I have not had any issues using these searches before today.  The channel search still works without any problems.

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at System.Threading.Tasks.Task.Execute()<---

Update
Now I get this error when using the channel search.

System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass45_0.<GetChannelIdByName>b__0()
   at TwitchLeecher.Services.Services.TwitchService.GetChannelIdByName(String channel)
   at TwitchLeecher.Services.Services.TwitchService.ChannelExists(String channel)
   at TwitchLeecher.Gui.ViewModels.SearchViewVM.Validate(String propertyName)
   at TwitchLeecher.Gui.ViewModels.SearchViewVM.Search()

Update 2
Rebooting my modem got rid of the error when using the channel search, but I'm still getting the error from using the ID and Url search.

**Comment by Franiac** [comment]
I cannot confirm this issue. The 401 Unauthorized response points towards Twitch server maintenance or other server shenanigans.

If you still get an error please provide the urls you are trying to get.

**Comment by ifusayso** [comment]
I just tested it with this VOD - 170027182.  Still getting the error.  It doesn't matter what Url or VOD ID I use.  I have tried on two different computers, one has win10 the other win8.1.  I have also tried version 1.3.8 and 1.3.9 on both computers and still no luck.  It's just weird that it was working fine the other day.

**Comment by Franiac** [comment]
The given ID works perfectly. Since noone else has submitted a similar issue I assume the problem is on your end. Maybe firewall settings or something?

**Comment by ifusayso** [comment]
I uninstalled and reinstalled deleting user settings. It worked until I linked my twitch account to access subscribed VODs.

**Comment by Franiac** [comment]
Does it work again if you revoke authentication?

**Comment by ifusayso** [comment]
Yes it does.

**Comment by Franiac** [comment]
Now i can reproduce it. If I authenticate, it fails. Weirdly enough the access token is valid. So there's a contradiction. Because of that there is a possibility that Twitch has temporary problems and therefor they are rejecting calls to the API including an Auth token. The other possibility is that they changed it permanently. I will track this a few days before I start messing around with code that may be obsolete if it is temporary.

**Comment by ifusayso** [comment]
OK.

**Comment by Franiac** [comment]
I scanned the code and removed unnecessary authentication headers from web requests. Problem solved with next update...

**Comment by joseph1125** [comment]
Looking forward to the next update!
