### ISSUE TITLE
URL Search not working

### ISSUE THREAD

**Issue by Temmie45** [Franiac/TwitchLeecher#180]
Whenever I try to search using a URL it says there was an unexpected error and generates this log file:

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at System.Threading.Tasks.Task.Execute()<---

The same thing happens when I try to search using an ID. Weirdly this only started happening today.

**Comment by Franiac** [comment]
See #176
