### ISSUE TITLE
Error (sometimes) when download tries to start

### ISSUE THREAD

**Issue by ifusayso** [Franiac/TwitchLeecher#183]
I've been getting this error frequently over the past several weeks. I was getting it with 1.3.9 and I am still getting it with 1.4.1. I cannot reproduce it, It just happens at random. Sometimes it takes several tries to get a vod to start downloading after getting this error and other times it starts right away. It can be several days before I get this error or I can get it several times in one day. I have been getting this error more frequently the past several days though, at least 6 times today, whereas before I'd get this error about once a day.

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by midniteghost** [comment]
Same problem here and appears to be random since I can restart the same download several times and eventually it gets past the error.

**Comment by Franiac** [comment]
Interesting that is does not fail every time. My guess is that it depends on the Tiwtch server you'll get redirected to if it works or not. Anything else makes no sense.

I know this error from other pieces of software. Usually it happens, when the client (in this case TL) does not accept the server's security certificate for the SSL tunnel.

@ifusayso @midniteghost I potentially have a fix soon but I want to test it. I cannot validate it, since I don't get the error. Would you be so kind to test a pre-release build (without installation) of TL in order to make sure we have a valid solution? If so, please send me an e-mail to contact@fakesmilerevolution.com so I have your address. I will provide you with a link to a download when it is ready.

**Comment by Franiac** [comment]
@ifusayso tested a pre-build version of TL 1.4.2 several days without getting a single error. I declare the bug fixed...
