### ISSUE TITLE
Unable to download VOD v1.4.2

### ISSUE THREAD

**Issue by shredmer** [Franiac/TwitchLeecher#213]
I have attempted to download this vod several times to different directories but have been unsuccessful. Each time it fails at the same step right at the end. It will finish the "Downloading" phase, go into "Processing" then near the end of processing, it will throw the red "Error" text. Log provided below:

Twitch Leacher v1.4.2
Channel: https://www.twitch.tv/nightfire001
VOD: https://www.twitch.tv/videos/214016443
OS: Windows 10 64bit
LOG:

```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 214016443
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/214016443
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Andy\Downloads\20171230_214016443_Counter-Strike_ Global Offensive.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Andy\AppData\Local\Temp\TL_445520e2-5a21-48b0-b6ad-e493ff378b39

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A214016443%2C%22expires%22%3A1515164113%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: f48cd274c95c4372c72fc8a128b8076bb9926fd6
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Andy\AppData\Local\Temp\TL_445520e2-5a21-48b0-b6ad-e493ff378b39'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/chunked/index-muted-CRWCHTY0Q9.m3u8
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/720p60/index-muted-CRWCHTY0Q9.m3u8
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/480p30/index-muted-CRWCHTY0Q9.m3u8
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/audio_only/index-muted-CRWCHTY0Q9.m3u8
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/360p30/index-muted-CRWCHTY0Q9.m3u8
https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/160p30/index-muted-CRWCHTY0Q9.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod.edgecast.hls.ttvnw.net/941efc151c5f288e0469_nightfire001_27125554432_764017322/chunked/index-muted-CRWCHTY0Q9.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 3320

Starting parallel video chunk download
Number of video chunks to download: 3320
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Andy\AppData\Local\Temp\TL_445520e2-5a21-48b0-b6ad-e493ff378b39\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\Andy\AppData\Local\Temp\TL_445520e2-5a21-48b0-b6ad-e493ff378b39\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Andy\Downloads\20171230_214016443_Counter-Strike_ Global Offensive.mp4"


Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Andy\AppData\Local\Temp\TL_445520e2-5a21-48b0-b6ad-e493ff378b39'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by shredmer** [comment]
There is also an mp4 file that is downloaded with a file size of 4.7GB in my Downloads file for this VOD but when attempting to open it throws the following error: "This file isn't playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt."

**Comment by Franiac** [comment]
See #156 and #143

**Comment by shredmer** [comment]
Thanks for the quick response. I actually was able to successfully download the VOD, at source quality, by breaking up the download into five separate 1 hour downloads. Instead of attempting to download the entire 5hour VOD at once. Something interesting is how before the failed download file was 4.7gb after attempting processing. Whereas the 5 separate clips add up to 9.27gb. Not sure if that is helpful to know at all

**Comment by Franiac** [comment]
Usually there is a point in the VOD where FFMPEG decides to fuck things up (many times because th4e streamer dropped frames). The resulting file is exactly the video size up to that specific point but unreadable because it get not closed properly and the end of the container is not written to the disk resulting in a corrupt file. In most cases cropping is the valid solution.
