### ISSUE TITLE
The remote server returned an error: (406) Not Acceptable.

### ISSUE THREAD

**Issue by Svish** [Franiac/TwitchLeecher#227]
When it's been downloading for a while (slow connection, which is why I download cause streaming doesn't really work... 😢), eventually it seems to hit this point where one video, and all the ones following it, fails with the error `The remote server returned an error: (406) Not Acceptable.`

The progress stands on 100%, but that's maybe just because failing is also a "completed" task. Hitting the retry button seems to immediately fail too, with the same error. At least the Log still says the same as far as I can see. Below is a copy of the log for the first and following download tasks that failed here now. It has happened once before too, but didn't think of reporting it...

**First failed**

```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 227638638
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/227638638
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\Downloads\_Twitch\20180210 - Subnautica Stream #8.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\tmp\twitch\TL_9c8f8924-5944-47c3-a09a-39f3473e788a

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3A57709057%2C%22vod_id%22%3A227638638%2C%22expires%22%3A1518613513%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 3177b21a2cdb25643a72752d828ba839ae32b643
Sub-Only: No
Privileged: No

Creating directory 'D:\tmp\twitch\TL_9c8f8924-5944-47c3-a09a-39f3473e788a'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\tmp\twitch\TL_9c8f8924-5944-47c3-a09a-39f3473e788a'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Following failed**

```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 228008058
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/228008058
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\Downloads\_Twitch\20180211 - Subnautica Stream #10.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\tmp\twitch\TL_ff358b2e-8e4f-4d84-81d2-e8d811452f49

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3A57709057%2C%22vod_id%22%3A228008058%2C%22expires%22%3A1518613525%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: bbdeea396322f290e4933420eaf7ae287a12c66c
Sub-Only: No
Privileged: No

Creating directory 'D:\tmp\twitch\TL_ff358b2e-8e4f-4d84-81d2-e8d811452f49'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\tmp\twitch\TL_ff358b2e-8e4f-4d84-81d2-e8d811452f49'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Svish** [comment]
Oh, and deleting the task and fully restarting the download as a new download task does seem to work fine, even though the retry for some reason fails.

**Comment by Franiac** [comment]
I don't think I can help unfortunately. The given VOD url downloads without any problems on my side so I cannot reproduce the problem. The 406 makes no sense at all since it is usually related to Access-Headers. But I don't use those in TL at all. The only thing that comes to my mind is a really bad hickup due to the slow or unstable connection.

TL tries to download the VOD playlists from the server and uses

`System.Net.WebClient.DownloadString`

for it. If that returns an error such as yours, there's nothing I can do about it. I have never seen TL failing on that part of the downloading process and it got never reported before. So I unfortunately have to assume it's on your end (given the fact that I can download the VOd without any problems).
