### ISSUE TITLE
Twitch Leecher can't download one 6hr long VOD but it can download other VODs from same streamer no problem

### ISSUE THREAD

**Issue by MarcoAntonioMartinez** [Franiac/TwitchLeecher#232]
For some reason I always get an error downloading this one VOD. I was thinking it was because of the length so I changed it to 17 minutes and 49 seconds and that works but any longer it will give me an error. I haven't tried 18 or 19 minutes but 20 minutes doesn't work either. I attached the log here. The streamer is called dookieshed and the VOD is the one recorded on 1/10/2018 and is Monster Hunter Generations. I am using version 1.4.2.

Start of log:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 217336599
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/217336599
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Marco\Downloads\20180110_217336599_Monster Hunter Generations__.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Marco\AppData\Local\Temp\TL_6fb41094-7d99-42c4-be22-0e95945eb16e

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A217336599%2C%22expires%22%3A1520549981%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: d3eebb010815320fa0b3358ba1aea53249812a39
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Marco\AppData\Local\Temp\TL_6fb41094-7d99-42c4-be22-0e95945eb16e'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@30fps (Source) is https://vod-secure.twitch.tv/f6fb0e1bf952eccbd56e_dookieshed_27233011632_770733397/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 3779

Starting parallel video chunk download
Number of video chunks to download: 3779
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Marco\AppData\Local\Temp\TL_6fb41094-7d99-42c4-be22-0e95945eb16e'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #3) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #4) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #5) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #6) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #7) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #8) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by Franiac** [comment]
Here's the important part or the log:

"System.IO.IOException: There is not enough space on the disk"

Says it all, right? 😄
