### ISSUE TITLE
Searching VOD with new update

### ISSUE THREAD

**Issue by iyalniz** [Franiac/TwitchLeecher#243]
I can not search the vods : https://imgur.com/a/JsGhI7X - https://imgur.com/a/7alaydB

LOG File :

 System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Internet cutout or server down. The last update did not include any changes to url's or the API. Same as 1.4.2. So just try again in a few hours or so.

**Comment by witnessmenow** [comment]
Just to confirm I'm seeing the same issue in 1.4.2 so not related to the update

**Comment by Franiac** [comment]
Ok, have you checked your firewall? 1.4.2 has been downloaded over 150000 times... nobody had this issue so there is a very high possibility that the problem is on your end. The "remote name api.twitch.tv could not be resolved" points towards a DNS/network misconfiguration on your end. I think TL cannot do anything here, unfortunately

**Comment by Franiac** [comment]
@witnessmenow 1.4.2 and 1.4.3 running perfectly here... cannot reproduce the issue.

**Comment by witnessmenow** [comment]
Working now for me (haven't changed anything)

**Comment by Franiac** [comment]
@witnessmenow Twitch servers are only human.... everyone has a bad day once in a while 😄
