### ISSUE TITLE
It does not work behind a proxy

### ISSUE THREAD

**Issue by JavikusRod** [Franiac/TwitchLeecher#246]
## Great work  with the dowloader , but you can add proxy settings?

this is the error when you are behind a proxy

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
@JavikusRod Would it be sufficient to implement getting the proxy settings from Windows? More specifically the settings you specify in Control Panel -> Internet Options -> Connections -> LAN Settings.

Otherwise we needed a whole new setting dialog and so on. I want to keep it simple because 99.9% of the useres are not behind a proxy anyways.

**Comment by JavikusRod** [comment]
Thanks for answering. I have to use another tool for that. Can you recommend me one that works behind proxys?

**Comment by Franiac** [comment]
What do you mean? We're talking about implementing proxy settings into TL so you could use it and now you want an alternative? I am confused... What exactly do you need now?

**Comment by JavikusRod** [comment]
I'm need the proxy settings, but you say you want to keep it simple. Then i ask if you know another tool that works beheind proxy. Sorry for my english

**Comment by Franiac** [comment]
Maybe we have a misunderstanding. There is a difference between implementing the windows proxy settings and specifying proxy settings in TL directly.

The first option would be that TL asks Windows about the proxy settings and applies them so that TL works behind the proxy. The downside of this approach is that you have to define the proxy settings in Windows and not in TL.

The second option is to implement the proxy setting within TL, so you can specify the settings directly in TL. Logically this would be much more complicated that the first approach.

What I wanted to know from you is if the first option would be ok for you.

**Comment by JavikusRod** [comment]
Yes the first option works for me, dude you are the best!!! thanks

**Comment by Franiac** [comment]
Should be working in the next update
