### ISSUE TITLE
Can not search video from URLs

### ISSUE THREAD

**Issue by dancof** [Franiac/TwitchLeecher#274]
Hi mate,
I can not search VOD from URLs. Example : https://www.twitch.tv/videos/281536706
Here are my description on log file. Can you help me with that. Thank you and have a nice day!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
#266 and #243
