### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by weedismyflower** [Franiac/TwitchLeecher#279]
Windows 10 64 bit
Version 1.4.2
Video https://www.twitch.tv/videos/286542401
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 286542401
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/286542401
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Davey x Angella\Videos\Monaim\20180719_286542401_Creative.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Davey x Angella\AppData\Local\Temp\TL_b30f72ff-c5a7-46ef-9f1f-f7c4bd1556e7

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1532092503%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A286542401%7D
Signature: 2bd57319a15db7b89ac211641591a852a17a4d98
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Davey x Angella\AppData\Local\Temp\TL_b30f72ff-c5a7-46ef-9f1f-f7c4bd1556e7'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/index-muted-BS0ANWW0AO.m3u8
https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/audio_only/index-muted-BS0ANWW0AO.m3u8

Playlist url for selected quality 1920x1080@30fps (Source) is https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/index-muted-BS0ANWW0AO.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1295

Starting parallel video chunk download
Number of video chunks to download: 1295
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Davey x Angella\AppData\Local\Temp\TL_b30f72ff-c5a7-46ef-9f1f-f7c4bd1556e7'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by Franiac** [comment]
The playlist of the video contains parts that are not downloadable.

You can download this part for example (try in your browser):

https://vod.edgecast.hls.ttvnw.net/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1087.ts

But this one (from the error message) not:

https://vod.edgecast.hls.ttvnw.net/b866f4b95ebad28ca66c_slrkwnsgh1_29543631792_915147150/chunked/1180-muted.ts

There is nothing wrong with TL. The Twitch playlist obviously contain files that are not available on the Twitch servers. Don't ask me why, but that's how it is.

What you can do is manually crop out the muted parts.
