### ISSUE TITLE
Immediate error message when attempting to download VOD "System.BadImageFormatException"

### ISSUE THREAD

**Issue by Liamcal01** [Franiac/TwitchLeecher#285]
Twitch Leecher Version: 1.5.3

Twitch VOD URL: https://www.twitch.tv/videos/288508176##

Windows 10 Pro 64 bit: 10.0.17134 build 17134

The problem: When I attempt to download my 2 hour long VOD from a couple of nights ago, I am immediately prompted with a red error message stating to check the output log. The output log states the following: 

"System.BadImageFormatException: Could not load file or assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]."

The only thing I did since downloading the program was to change the download directories to my 500GB hard drive which is NOT my OS hard drive. My OS hard drive is a tiny SSD. In regards to the assembly binding issue, I followed those directions and edited the registry value and tried to do it again, this time getting a log with the following: 

"System.BadImageFormatException: Could not load file or assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

=== Pre-bind state information ===
LOG: DisplayName = System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///D:/Programs/Twitch Leecher/
LOG: Initial PrivatePath = NULL
Calling assembly : TwitchLeecher.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\Programs\Twitch Leecher\TwitchLeecher.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

Since it did not solve the problem to edit that registry, I reverted the registry back to how it was in the initial output log error file. Any help would be greatly appreciated! :D

**Comment by Liamcal01** [comment]
Quick note: I am trying to download my own video, so I didn't bother signing in to bypass sub only VODs. That being said, it would be a good idea for me to try signing in just in case: I tried to do so and the software crashed with a UI error :/

**Comment by Franiac** [comment]
That does not look like something is wrong with TL.

`Could not load file or assembly 'System.Web'`

The System.Web.dll is part of the .NET framework (which is again part of Windows) and is located in the .NET Framework base folder and is registered in the GAC (Global Assembly Chache). So this file is not shipped with TL or copied to your system during installation.

`The module was expected to contain an assembly manifest`

If the System.Web.dll does not contain an assembly manifest shit got cooked farely hot.
I don't really have a concrete direction but you could try to re-install or update the .NET 4 Framework.

But again, this is not something TL causes. TL uses the System.Web.dll, yes, but it is not responsible for its existence or its assembly manifest.

**Comment by Liamcal01** [comment]
Interesting stuff, thank you. Coincidentally, today my SSD failed and completely crapped out on me, and I have been having a lot of PC issues lately. I think it may have been related to that. Thank you anyway though lol
