### ISSUE TITLE
"Not enough space on disk" error only on 6 hour+ VODs with 200+GB space available

### ISSUE THREAD

**Issue by sinfinite** [Franiac/TwitchLeecher#289]
This issue is only happening with VODs over 6 hours long, as i had a few other slightly shorter VODs queued between some of the longer ones, and those downloaded fine. i have 217GB of space still available where i'm downloading it to, so i'm not sure why this is giving me issues. The 5.5 hour VODs i downloaded run only about 13GB so i can't imagine the 6 and 8 hour ones are that much larger. Here is an example log from one of the downloads. Thanks!

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 286672013
Selected Quality: 1600x900@60fps (Source)
Download Url: https://www.twitch.tv/videos/286672013
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\VODS 2\20180719_023432PM_o_.mp4
FFMPEG Path: D:\Apps\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\temp\TL_e55a6a22-b930-406f-85d1-9a39281cd0ad

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1533429687%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A286672013%7D
Signature: 5853c698c9e530b9bcf78040c5d943a8a4e26ce9
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\temp\TL_e55a6a22-b930-406f-85d1-9a39281cd0ad'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/chunked/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/720p60/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/720p30/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/480p30/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/audio_only/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/360p30/index-dvr.m3u8
https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/160p30/index-dvr.m3u8

Playlist url for selected quality 1600x900@60fps (Source) is https://vod135-ttvnw.akamaized.net/ec6c38cf3ad14aac0eff_a_seagull_29548081824_915425277/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2327

Starting parallel video chunk download
Number of video chunks to download: 2327
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\temp\TL_e55a6a22-b930-406f-85d1-9a39281cd0ad'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #3) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #4) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #5) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #6) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #7) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #8) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by Franiac** [comment]
Be aware that you need twice the space on disk. 1st for the downloaded .ts files and 2nd for the mp4 file. When the ts. files are all downloaded, ffmpeg converts them into a mp4 file, so somewhere in the middle of the process you have 100gb .ts files AND a 100gb mp4 file on disk, before the ts file gets removed after conversion. A 6hr video can easily go beyond 100gb. that depends on the quality and the encoding settings of the streamer. And if TL sais that there is no space left, then ther is no space left. That message is not a funny prank. That is actually your Windows screaming for help, no TL 😄
