### ISSUE TITLE
Downloads all instantly fail if they are queued for too long

### ISSUE THREAD

**Issue by randomname42** [Franiac/TwitchLeecher#298]
I have slow net and recently used TL (1.5.3) pretty heavily, queuing up a lot of downloads at once. 

I happened to be at the pc the next day when a download finished--and then everything else I had queued up the day before instantly failed. Hitting the retry button on any of them just instantly failed again every time.

I double checked my internet and it was having no issues. 

I tried deleting a download from the list and re-adding it. That worked. I didn't even have to search again, just go to the search page that was already there and hit download.  Same thing for the other vods that had instantly failed and wouldn't retry.

Back to the refusal to start. I think it happened at somewhere around 20-24 hours after the downloads were added to the queue, if that helps. I'm guessing there's some kind of authorization to/from Twitch that happens when a download is first queued, and then after a certain amount of time (if the download hasn't been started before then) it expires? 

Given that all the downloads worked after deleting and re-adding them (without even having to search again), is there maybe a way that the authorization could happen right before a download actually starts, instead of when it's put into queue? Or, if some kind of authorization is needed to queue a download, could it be authorized again right before the download starts? You know, basically simulating that someone just manually deleted and re-added the download.

In any case here's the logs:

**VOD 1:** 

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 290347678
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/290347678
Crop Start: Yes (00:04:30)
Crop End: Yes (05:46:04)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\D\twitch\Cirno_TV 2018-07-28 Cirno plays Resident Evil! [Blind] [pls no bully] 720p30.mp4
FFMPEG Path: D:\Utils\vde\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\D\twitch\(temp)\TL_2316a3ff-13bc-4482-897c-4f73ac926496

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1536511766%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A290347678%7D
Signature: aba1d99d1f2d44dfd34664e3302ce49540a0cccd
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\D\twitch\(temp)\TL_2316a3ff-13bc-4482-897c-4f73ac926496'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\D\twitch\(temp)\TL_2316a3ff-13bc-4482-897c-4f73ac926496'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**VOD 2:**

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 290741850
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/290741850
Crop Start: Yes (02:24:18)
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\D\twitch\Cirno_TV 2018-07-29 More Resident Evil! 720p30.mp4
FFMPEG Path: D:\Utils\vde\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\D\twitch\(temp)\TL_f13a589d-c3c2-4a1b-b1c0-09a3e01fc506

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1536511855%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A290741850%7D
Signature: b552eccfb543e71fdad39c1927b6f7ed7178d3cf
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\D\twitch\(temp)\TL_f13a589d-c3c2-4a1b-b1c0-09a3e01fc506'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\D\twitch\(temp)\TL_f13a589d-c3c2-4a1b-b1c0-09a3e01fc506'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**VOD 3:**

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 290704743
Selected Quality: 1280x720@30fps (Source)
Download Url: https://www.twitch.tv/videos/290704743
Crop Start: Yes (07:03:19)
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\D\twitch\Spikevegeta 2018-07-29 OOT Rando -source720p30.mp4
FFMPEG Path: D:\Utils\vde\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\D\twitch\(temp)\TL_556f4d53-0a6b-4af8-a8cb-dd0e2e0c956c

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1536512138%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A290704743%7D
Signature: 7b059893408a8ab060928f57bcfbfb37b3341cff
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\D\twitch\(temp)\TL_556f4d53-0a6b-4af8-a8cb-dd0e2e0c956c'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\D\twitch\(temp)\TL_556f4d53-0a6b-4af8-a8cb-dd0e2e0c956c'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**VOD 4:**

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 291537303
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/291537303
Crop Start: Yes (00:08:09)
Crop End: Yes (03:13:34)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\D\twitch\Cirno_TV 2018-07-31 Resident Evil Finale! Last stream before heading to the states! 720p30.mp4
FFMPEG Path: D:\Utils\vde\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\D\twitch\(temp)\TL_f49d27a3-9a36-4b8c-a35f-0f346635e0b2

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1536512232%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A291537303%7D
Signature: d5d2b0483b0ad26395f300631bdc186cc1cc0180
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\D\twitch\(temp)\TL_f49d27a3-9a36-4b8c-a35f-0f346635e0b2'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'D:\D\twitch\(temp)\TL_f49d27a3-9a36-4b8c-a35f-0f346635e0b2'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
First off look at "VOD INFO" in the log:

```
Crop Start: Yes (00:04:30)
Crop End: Yes (05:46:04)
```
It's all there...

As for the queueing thing: TL was not built for heavy duty download queues. It once was a tool to download a single VOD for myself every week. It is surely a problem that the API access token expires after 24 hours, so whenever a download is deferred to a later point in time (as in >24h), it will fail because TL does not re-authorize to the API.

At the current state this implementation would be quite a lot of work and in all honesty I don't have the time for it right now and there are much more important features that need to be implemented first. So this runs at low priority.

**Comment by Franiac** [comment]
Closing this one because #46 will have this as a requirement anyways
