### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by ringtvt** [Franiac/TwitchLeecher#316]
Twichleecher 1.54
Win 8.1 64bit
Log: 01212019_083640_447_PM_error
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Franiac** [comment]
Yes, patience and try again later.Twitch issues or temporary DNS hickups.

Always check closed issues first and give new issues a meaningful title next time.
