### ISSUE TITLE
Error after downloading 3 hour VOD

### ISSUE THREAD

**Issue by xBrons** [Franiac/TwitchLeecher#333]
The file is about 3 hours and 10 mins long, I've attempted to download it onto my external HD with over 600 gigs of free space, and an internal with over 200 gigs of free space. Still displaying that there isn't enough disk space, so I'm not sure where to go from here.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 408319145
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/408319145
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: H:\Game Footage\apexstream.mp4
FFMPEG Path: E:\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: H:\Game Footage\TL_b8c8e3d5-9b2e-45f0-a349-14dc0f14ad6d

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1554903897%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A408319145%7D
Signature: b0a5591406000e27e0eb2b5a3f8868df06f92cf7
Sub-Only: No
Privileged: No

Creating temporary download directory 'H:\Game Footage\TL_b8c8e3d5-9b2e-45f0-a349-14dc0f14ad6d'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/070d7d16b6e9593e7227_rosey_ow_33604163280_1168905660/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/070d7d16b6e9593e7227_rosey_ow_33604163280_1168905660/audio_only/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps (Source) is https://vod-metro.twitch.tv/070d7d16b6e9593e7227_rosey_ow_33604163280_1168905660/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 917

Starting parallel video chunk download
Number of video chunks to download: 917
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'H:\Game Footage\TL_b8c8e3d5-9b2e-45f0-a349-14dc0f14ad6d\apexstream.ts'...

Starting temporary download folder cleanup!
Deleting directory 'H:\Game Footage\TL_b8c8e3d5-9b2e-45f0-a349-14dc0f14ad6d'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
This is not an error message that Twitch Leecher throws. Windows is telling TL that there is not enough space... TL only receives the message from the OS. I cannot do anything about this.
