### ISSUE TITLE
Instant error when downloading.

### ISSUE THREAD

**Issue by jonjonthewise** [Franiac/TwitchLeecher#361]
I get an immediate error when downloading. Here is the log. please let me know what I can do! I have updated to the most recent version of leecher, and this error has never happened before. 

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 449514627
Selected Quality: 1280x720@30fps (Source)
Download Url: https://www.twitch.tv/videos/449514627
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: K:\PODCAST EPISODES\20190707_449514627_Talk Shows & Podcasts.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\user\AppData\Local\Temp\TL_2b8f979e-8388-4ea9-8399-0b27dfc1d4af

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562637314%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A81878460%2C%22version%22%3A2%2C%22vod_id%22%3A449514627%7D
Signature: b8f404cdaa19e1e5ff88b42f993ed18a46ddbe68
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\user\AppData\Local\Temp\TL_2b8f979e-8388-4ea9-8399-0b27dfc1d4af'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\user\AppData\Local\Temp\TL_2b8f979e-8388-4ea9-8399-0b27dfc1d4af'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
No, you did not :)

1.5.8 is the latest version and this error is fixed.

**Comment by jonjonthewise** [comment]
Ah ok thank you.
