### ISSUE TITLE
error downloading vod

### ISSUE THREAD

**Issue by lordesssatan666666** [Franiac/TwitchLeecher#381]
Twitch Leecher 1.7
URL: https://www.twitch.tv/videos/485299056
Channel: SwaggerSouls
Windows 10 64 bit

When I download this (with default settings as well as changing download location, resolution, etc.) it immediately goes to 100% at error status.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 485299056
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/485299056
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\girgo\Downloads\20190923_485299056_Cube World.mp4
FFMPEG Path: D:\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\girgo\AppData\Local\Temp\TL_4432a5cf-8bd1-4592-aef0-9c4aca9e934b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1569531109%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A485299056%7D
Signature: 066c45903a42d7f38de8856194b07a7a629e56ba
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\girgo\AppData\Local\Temp\TL_4432a5cf-8bd1-4592-aef0-9c4aca9e934b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/15723971ca0af9da7f2a_swaggersouls_35753528208_1303277476/chunked/index-dvr.m3u8

Retrieving playlist...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\girgo\AppData\Local\Temp\TL_4432a5cf-8bd1-4592-aef0-9c4aca9e934b'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 13.224.2.28:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 13.224.2.28:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Perfectly fine here.

`Unable to connect to the remote server`

That's not a TL issue. Often just a temporary thing / internet hickup.
