### ISSUE TITLE
Recieving an error everytime I try to download VOD

### ISSUE THREAD

**Issue by KlauseRBoy** [Franiac/TwitchLeecher#386]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 490118723
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/490118723
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\AlexDoNotTouch\Programs\twitchleecher\LeBron\MeLeBron_20191004_League of Legends.mp4
FFMPEG Path: D:\AlexDoNotTouch\Programs\twitchleecher\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\AlexDoNotTouch\Programs\twitchleecher\TL_820592a9-ea89-4187-a31c-da0b64b3ce38

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1570398709%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A490118723%7D
Signature: 357328ea4be851267dd424c38afcf1ea658401ed
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\AlexDoNotTouch\Programs\twitchleecher\TL_820592a9-ea89-4187-a31c-da0b64b3ce38'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/720p60/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/720p30/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/480p30/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/audio_only/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/360p30/index-muted-4U3NCYTDNE.m3u8
https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/160p30/index-muted-4U3NCYTDNE.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/index-muted-4U3NCYTDNE.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2624

Starting parallel video chunk download
Number of video chunks to download: 2624
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'D:\AlexDoNotTouch\Programs\twitchleecher\TL_820592a9-ea89-4187-a31c-da0b64b3ce38'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/318d2fc98d7f50394ed9_melebron_35867361504_1310393248/chunked/1544.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
If you click one of the failed links you get an internal server error (Code 500) in the browser. This means Twitch messes up something on their servers (not delivering the requested file). This is not a TL issue, it's on Twitches' end, sorry :)
