### ISSUE TITLE
Upgrade Installation Failure Sequence

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#431]
Starting with 1.5.6 installed and .NET 4.7.

1) Launched TwitchLeecher_1.7.3.exe
2) Accepted and installed (.NET presumably)
3) System rebooted without prompting
4) On Startup Twitch Leecher prompted to upgrade 1.5.6 to 1.7.3
5) Failed to install as below log
(6) Launched same installer as in 1)
7) Twitch Leecher upgraded successfully

System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

![image](https://user-images.githubusercontent.com/14173022/69172692-29818800-0ab3-11ea-89f9-b248b1acc967.png)

**Comment by Franiac** [comment]
As far as I understand you managed to install 1.7.3 successfully now, correct?

**Comment by dsnvwlmnt** [comment]
Yes, I spent my time posting these issues to improve your program and for the benefit of future users. There is an issue in the sequence here and so I reported it for your benefit.

**Comment by Franiac** [comment]
> Yes, everything is good on my end, Or, good enough.

duuuuuuude. and you're wondering why a dev of a freetime project working for no money gets a little bit pissed on github? you can post issues here, yes. but in every post you made so far there is some judgemental vibe coming along, telling me how bullshit my tool is.

sorry for not investing 8 hours a day for a little boo-boo one single user happens to run into after half a million people using the installer without any problems for the past 2 1/2 years.
