### ISSUE TITLE
1.7.3 issue - Can't download videos

### ISSUE THREAD

**Issue by Emiliovaslord** [Franiac/TwitchLeecher#436]
I've tried downloading sub-only, and regular twitch vods. Here's the log: 

System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Boldkeeper** [comment]
Same thing here.

**Comment by Franiac** [comment]
#419
