### ISSUE TITLE
Remote Server returned an error

### ISSUE THREAD

**Issue by Heckyl** [Franiac/TwitchLeecher#438]
An unexpected error occured:
The remote server returned an error (410) Gone.
All details were written to log file

System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Heckyl** [comment]
Getting this with the latest version of Twitch Leecher.  1.7.3 
Was also getting this with an earlier version.
Can no longer reach videos for sub content.

**Comment by Franiac** [comment]
#419
