### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by Koppertone** [Franiac/TwitchLeecher#444]
ive not had any problems till the last few days and i continue to receive the following on each try:
Please advise how i can fix this.  Thanks in advance!!  :-)

**Download task ended with an error!**

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass60_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass60_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by peterenispeter** [comment]
Hey there,
I get Remote Server Error (410) not existing (translated from German)

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (410) Nicht vorhanden.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)


Same problem everytime I want to download from 2 different PCs. Before it was working perfectly on both. I did not change anything.

Thank you very much!

**Comment by Franiac** [comment]
No response - closed
