### ISSUE TITLE
prevent filename from being too long

### ISSUE THREAD

**Issue by gamepilot-d** [Franiac/TwitchLeecher#451]
windows 10 64 bit
using filename template: {date}\_{id}\_{channel}\_{game}\_{res}\_{fps}\_{title}

was able to successfully download when shortening the filename. would be nice to have a {title_truncated}.

download log:
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 508002721
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/508002721
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: E:\TwitchLeecher\FuturemanGaming\20191113_508002721_FuturemanGaming_Death Stranding_1920x1080_60_Save the Baby, Save the Future __ Futureman-- Nice Moves, Red Lobster w_ Hideo, Never Stop Encabulation, 56k Internet, Tight fmgBUNS.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1575607358%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A508002721%7D
Signature: 60e2a80fe811044ad65e546b9037732d7b9c4bdc
Sub-Only: No
Privileged: No

Creating temporary download directory 'E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/chunked/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/720p60/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/720p30/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/480p30/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/audio_only/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/360p30/index-muted-IDVHA8CSSI.m3u8
https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/160p30/index-muted-IDVHA8CSSI.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/c0691cbc6170e30f1953_futuremangaming_36208961808_1331755948/chunked/index-muted-IDVHA8CSSI.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2118

Starting parallel video chunk download
Number of video chunks to download: 2118
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb\20191113_508002721_FuturemanGaming_Death Stranding_1920x1080_60_Save the Baby, Save the Future __ Futureman-- Nice Moves, Red Lobster w_ Hideo, Never Stop Encabulation, 56k Internet, Tight fmgBUNS.ts'...

Starting temporary download folder cleanup!
Deleting directory 'E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb\20191113_508002721_FuturemanGaming_Death Stranding_1920x1080_60_Save the Baby, Save the Future __ Futureman-- Nice Moves, Red Lobster w_ Hideo, Never Stop Encabulation, 56k Internet, Tight fmgBUNS.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\TwitchLeecher\temp\TL_8f78861f-e460-4559-8b2d-5c0794517bdb\20191113_508002721_FuturemanGaming_Death Stranding_1920x1080_60_Save the Baby, Save the Future __ Futureman-- Nice Moves, Red Lobster w_ Hideo, Never Stop Encabulation, 56k Internet, Tight fmgBUNS.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Franiac** [comment]
Truncating the title is only half of the truth since it is not necessarily the longest part of the complete path. A NTFS filename is limited to 259 characters including all subdirectories and the filename. So if we truncate the title to let's say 100 chars but someone stacks directories the filename can still be too long.

A first check would be that the generated filename is not longer than 259 chars. If it is too long I could automatically truncate the title so that the filename fits. If this is not possible because of directory-stacking you have to use the custom filename checkbox.

This would probably solve 98% of the occurances (because usually the problem is the long title). The remaining 2% cannot be solved automatically.

**Comment by gamepilot-d** [comment]
makes sense. you really wouldn't want it to take up all available characters anyway cause you might want to move it to a new directory structure later. i would suggest a user settable truncate length, something like {title_50}, and force the user to edit the filename if the full path exceeds the limit before allowing the download.

**Comment by stijndp** [comment]
I'd catch PathTooLongException in StartQueuedDownloadIfExists for the temp folder.
(Personally I would ditch the temp folder in preferences and use Path.GetTempPath to be sure if errors happen, which could be losing power to the system or other programs causing an exit, that Windows will still cleanup the trash.)

For the final file destination you could brute force the user under 260 characters even on systems that allow higher. Then an extra validation on both Folder and Filename in DownloadParameters should suffice.
```
else if (FullPath.Length >= 260)
{
	AddError(currentProperty, "Folder and filename can't be longer than 260 characters. Choose a different download folder or use a custom filename.");
}
```

It gets messy quickly trying to check for longer paths allowed on Windows 10 starting from build xxx and below it's still possible with Windows 10 but if a certain registry key is set and below Windows 10 ... and if the user is actually on Linux ...

**Comment by Codereaders** [comment]
@Franiac If you try to put an empty (temporary) file at the user selected location right after focus loss from the selection field, you could find out whether it is a valid path + filename length. In case of an error you can highlight the field and prevent from enqueuing the download. It's not really a very elegant way, but should work.

Putting the file into a folder not selected by the user is weird and absolutely unintuitive. Might even lead to questions and complains.

**Comment by Franiac** [comment]
I added a validation for a maximum full path length of 250 characters. The automated truncating of the title feels odd when it is cut just in the middle of a word, so I did not inclkude that change.
