### ISSUE TITLE
Search Problem

### ISSUE THREAD

**Issue by DSE14th** [Franiac/TwitchLeecher#460]
Im using the 1.8 version right now and seems to have trouble when trying to search this VOD 

https://www.twitch.tv/videos/521427290

Dont really have any exp when dealing with this kind of tech problem so pls tell me what kind of info you need more

My log file :

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.twitch.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   at TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Hmm, works for me, tho...

Maybe give it a try later or tomorrow again?
