### ISSUE TITLE
An unexpected error occurred when launching app

### ISSUE THREAD

**Issue by fidorulz** [Franiac/TwitchLeecher#461]
using 1.8. startted getting  this error today

log file

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by fidorulz** [comment]
opened in error
