### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by RonnieBlaze** [Franiac/TwitchLeecher#502]
I have tried searching from two different networks (in case twitch banned my ip address) and both networks can not search. It could be a twitch problem and will resolve its self. But here is the error when searching

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
An internal server error 500 happens when the request gets processed by the server and the executed code throws an unexpected error that does not get caught by an error handling mechanism. In other words: Twitch messed up 😄
