### ISSUE TITLE
Found 2 videos that wont download.

### ISSUE THREAD

**Issue by RonnieBlaze** [Franiac/TwitchLeecher#505]
I have been trying to back up  Reckfuls vod since is passing, and i have come across 2 videos that wont download.

https://www.twitch.tv/videos/289149078
https://www.twitch.tv/videos/290713788

Errors Below

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 289149078
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/289149078
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: F:\reckful\20180725_030234PM - Reckful - Reckful - back in austin after 4 months !_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Ron\AppData\Local\Temp\TL_1cb13641-697f-4ef2-93ec-794ff5445e95

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1596012269%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A289149078%7D
Signature: 8a8bf0ddf6f37e9eb8fe5601848e66ca07b5e5bb
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Ron\AppData\Local\Temp\TL_1cb13641-697f-4ef2-93ec-794ff5445e95'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/720p60/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/720p30/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/480p30/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/audio_only/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/360p30/index-muted-9W70HTAMDN.m3u8
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/160p30/index-muted-9W70HTAMDN.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/index-muted-9W70HTAMDN.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1788

Starting parallel video chunk download
Number of video chunks to download: 1788
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Ron\AppData\Local\Temp\TL_1cb13641-697f-4ef2-93ec-794ff5445e95'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

The chunk file 17.ts all the way to 71.ts gives the AccessDenied error.   Is there a way to make it continue but skip the chunks it can not find?

**Comment by Franiac** [comment]
Happens when Twitch somehow messes up the permissions on single VOD parts from the playlist. Can't do anything about it since it is server-side, sorry.

**Comment by lay295** [comment]
I was just browsing issues and stumbled upon this one. It seems segments 17-35 are actually muted but don't show up as muted in the m3u8 playlist. So the original file is actually just deleted.

Because the muted segment exists
https://dqrpb9wgowsf5.cloudfront.net/aeb89a2be714ed13d345_reckful_29636822448_920971566/chunked/17-muted.ts

A possible fix would maybe to just attempt to download a muted segment if a regular segment fails?

**Comment by Franiac** [comment]
@lay295 May be a valid workaround... but I'd rather see Twitch fixing their crap alone 😄
