### ISSUE TITLE
Won't download random video.

### ISSUE THREAD

**Issue by Legotron123** [Franiac/TwitchLeecher#517]
It downloads every other video on the channel (rickpgriffon), so I'm not sure why it won't download this one (https://www.twitch.tv/videos/728757074). Here's the download log.
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 728757074
Selected Quality: 1280x720@30fps (Source)
Download Url: https://www.twitch.tv/videos/728757074
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\legot\Videos\Rick's Twitch Streams\20200901_728757074_Paper Mario_ The Origami King.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\legot\AppData\Local\Temp\TL_07b6f5dc-2cc8-4595-86ef-c77b646e92f3

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1599260001%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A728757074%7D
Signature: d88365550744fd854a30882c67c51613750438a9
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\legot\AppData\Local\Temp\TL_07b6f5dc-2cc8-4595-86ef-c77b646e92f3'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/720p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/480p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/audio_only/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/360p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@30fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4026

Starting parallel video chunk download
Number of video chunks to download: 4026
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296664@0' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:335204@883788' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:290648@1195680' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296476@886984' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:297228@1183460' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:287828@566256' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:329564@0' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:268652@324676' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296664@0' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:290648@1195680' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:287828@566256' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:329564@0' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:297228@1183460' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:335204@883788' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296476@886984' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:268652@324676' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296664@0' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:297228@1183460' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296476@886984' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:335204@883788' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:287828@566256' failed! Trying again in 20s

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:290648@1195680' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:329564@0' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:268652@324676' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\legot\AppData\Local\Temp\TL_07b6f5dc-2cc8-4595-86ef-c77b646e92f3'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:294972@295348' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296664@0' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #2) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:296476@886984' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #3) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:297228@1183460' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #4) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:290648@1195680' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #5) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:329564@0' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #6) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:335204@883788' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #7) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:268652@324676' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #8) System.ApplicationException: Could not download file 'https://dqrpb9wgowsf5.cloudfront.net/81faa62377938fbed6f9_rickpgriffin_39520993934_1599015391/chunked/#EXT-X-BYTERANGE:287828@566256' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Legotron123** [comment]
Did some digging, and there are a few people on twitter complaining about this too, with some of them mentioning that Twitch did something with their playlist format on the first that affected streams recorded on that day. If that's they case, we have until the fifteenth to find a work around before a lot of videos are lost forever.

**Comment by Codereaders** [comment]
https://github.com/Franiac/TwitchLeecher/issues/514

**Comment by Legotron123** [comment]
Yeah, I didn’t notice that until after I posted this. I’m a doofus.
