### ISSUE TITLE
Vod Download Error

### ISSUE THREAD

**Issue by kos277** [Franiac/TwitchLeecher#530]
Hi. I am trying to download all my vods, and it worked fine for the first 12 and now i keep getting Error.

I am using Twitch Leecher 1.8.1 on Windows 10 64bit

LOG:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.1

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 775119408
Selected Quality: 1920x1080@50fps (Source)
Download Url: https://www.twitch.tv/videos/775119408
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\soren\Downloads\20201019_775119408_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\soren\AppData\Local\Temp\TL_f7e8c298-6d3a-4853-873e-870a1623a3a6

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1603518856%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A775119408%7D
Signature: 2572475457171646f10102a8ada89cba4547ecf3
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\soren\AppData\Local\Temp\TL_f7e8c298-6d3a-4853-873e-870a1623a3a6'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/highlight-775119408.m3u8
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/720p60/highlight-775119408.m3u8
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/480p30/highlight-775119408.m3u8
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/audio_only/highlight-775119408.m3u8
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/360p30/highlight-775119408.m3u8
https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/160p30/highlight-775119408.m3u8

Playlist url for selected quality 1920x1080@50fps (Source) is https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/highlight-775119408.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 969

Starting parallel video chunk download
Number of video chunks to download: 969
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\soren\AppData\Local\Temp\TL_f7e8c298-6d3a-4853-873e-870a1623a3a6'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d2nvs31859zcd8.cloudfront.net/455d1d0900bf79fabe1c_snugtheplug_74200687788_2448176485/chunked/856-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
Twitch fucked up again. There are files in the playlist that cannto be accessed (error 403). It happens every now and then. Not a TL issue, though 😃

**Comment by kos277** [comment]
The same vod that twitch leecher is unable to download was succesful with https://youtube-dl.org/ 
Unfortunately i will have to manually do every single vod and I have 400 but at least it works
