### ISSUE TITLE
Any Suggestion

### ISSUE THREAD

**Issue by Alan-Python** [Franiac/TwitchLeecher#534]
System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

READ THIS FIRST!!!

Help me beeing efficient, please! I am developing Twitch Leecher in my free time for no money. Contribute to the project by posting complete, structured and helpful issues which I can reproduce quickly without asking for missing information.

When creating a new issue please make sure you follow the below checklist:

- Take a look at the latest closed issues. Maybe yours has already been solved.
- If you have a problem with a download, provide the download log created by Twitch Leecher
- Provide the version of Twitch Leecher you are using
- Provide information about the video (Url, Channel, ID)
- Provide information about your operating system (e.g. Windows 10 64 Bit)
- Try to describe the problem as detailed as possible, I cannot read your mind
- Windows Insider Builds are NOT supported!

About Audio/Video Desync Issues:

Make sure to check for desync issues with VLC Media Player. A lot of video tools have immense trouble playing back downloaded Twitch streams correctly. Especially the following products introduce A/V desync:

- Windows Media Player
- Adobe Premiere (no joke, Adobe just does not care)

So if you are about to post a desync issue and you are using one of the above programs, please check the video in VLC first!

-->

**Comment by Franiac** [comment]
Please post the complete log of the download.

**Comment by Alan-Python** [comment]
How do I do that?

**Comment by Franiac** [comment]
[https://github.com/Franiac/TwitchLeecher#support--issues](https://github.com/Franiac/TwitchLeecher#support--issues)

**Comment by Franiac** [comment]
Closed because stale
