### ISSUE TITLE
[Error]An unexpected error occurred(when searching)

### ISSUE THREAD

**Issue by ChinryZhu** [Franiac/TwitchLeecher#559]
Version: 1.8.2
System: Win10
.NET framework 4.5 has been already installed.

Search for videos and fail. 

Details: 
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
    --- End of inner exception stack trace ---
    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
    at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
    at System.Net.ConnectStream.WriteHeaders(Boolean async)
     --- End of inner exception stack trace ---
    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
    at System.Net.WebClient.DownloadString(Uri address)
    at TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
    at TwitchLeecher.Services.Services.TwitchService.SearchUrls(String urls)
    at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
    at System.Threading.Tasks.Task.Execute()
     --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
    --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

**Comment by Franiac** [comment]
This happens occasionally. The Twitch API servers just reject the call.

`The underlying connection was closed`

I don't know why, but sometimes requests to the Twitch API don't get through because the server says "No". I suppose after trying again it worked?

**Comment by Alvaro203204** [comment]
The same thing happens to me and no matter how hard I try, I get the same error

**Comment by Franiac** [comment]
Without you providing the lacking information, I can't help. What are your search parameters and so on. Please read the issue template and post accordingly.

**Comment by ChinryZhu** [comment]
> Without you providing the lacking information, I can't help. What are your search parameters and so on. Please read the issue template and post accordingly.

I've tried several different IDs (not deleted yet), like 881699028, 879848373. And it just didn't work.

**Comment by Tacetee** [comment]
Same, I cant download any video now, it finds the video but as soon as I hit download, it pops up the error message.

**Comment by Franiac** [comment]
@ChinryZhu your ID's work just fine here in TL 1.8.2

@Tacetee do you have 1.8.2 installed, because that sound an awful lot like #550

**Comment by Tacetee** [comment]
You are right sorry, it didnt tell me there was a new version. I just downloaded 2 and it works fine now, came here to delete my message but too late lol. Thanks.

**Comment by ChinryZhu** [comment]
> @ChinryZhu your ID's work just fine here in TL 1.8.2
> 
> @Tacetee do you have 1.8.2 installed, because that sound an awful lot like #550

I'm just thinking if there's something wrong with my PC (the problem is that I can't find out) as it keeps popping up the same kind of error message
