### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by MIFUNEKINSKi** [Franiac/TwitchLeecher#597]
Thank you for the wonderful app!  using latest version, attemping to download https://www.twitch.tv/videos/999189725 - User: yesitshappy.  Windows 10 Home.  The video seems to download and I see the file downloaded, it just won't play.  The file size seems to also be correct.  I get an error at the very end of downloading when it tries to compile the files.  

Thanks for all you do! I attempted twice following a computer restart, and I also attempted on 1.82 and had the same issue.  Here are the two error logs.  

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 999189725
Selected Quality: 1920x1080@61fps (Source)
Download Url: https://www.twitch.tv/videos/999189725
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Chris\Downloads\20210424_9991897251_Warcraft III.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Chris\AppData\Local\Temp\TL_b394f8b5-565a-4e15-8b8f-90883c28a397

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1619363264%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A999189725%7D
Signature: 4f266fdf6521a5017386d2ac436b65617aad6eef
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Chris\AppData\Local\Temp\TL_b394f8b5-565a-4e15-8b8f-90883c28a397'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/chunked/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/720p60/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/480p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/audio_only/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/360p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@61fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1662

Starting parallel video chunk download
Number of video chunks to download: 1662
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Chris\AppData\Local\Temp\TL_b394f8b5-565a-4e15-8b8f-90883c28a397'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #2) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #3) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #4) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #5) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #6) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #7) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #8) System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

------++++++++++++++++++++

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 999189725
Selected Quality: 1920x1080@61fps (Source)
Download Url: https://www.twitch.tv/videos/999189725
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Chris\Downloads\20210424_999189725_Warcraft III.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1619360808%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A999189725%7D
Signature: f8cdcabe2b2391bee3db37a128fcfae2e7bec6fd
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/chunked/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/720p60/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/480p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/audio_only/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/360p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@61fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/8d495db9a09b4e823fda_yesitshappy_41865861388_1619274634/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1416

Starting parallel video chunk download
Number of video chunks to download: 1416
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0\20210424_999189725_Warcraft III.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0\20210424_999189725_Warcraft III.ts'...
Command line arguments: -y -i "C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0\20210424_999189725_Warcraft III.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\Chris\Downloads\20210424_999189725_Warcraft III.mp4"

ffmpeg version 4.3.2-2021-02-27-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0\20210424_999189725_Warcraft III.ts':
Duration: 03:56:00.04, start: 68.007000, bitrate: 6411 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 149 kb/s
Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 90k tbn, 120 tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'C:\Users\Chris\Downloads\20210424_999189725_Warcraft III.mp4':
Metadata:
encoder         : Lavf58.45.100
Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 90k tbn, 90k tbc
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 149 kb/s
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 7303 fps=0.0 q=-1.0 size=   91392kB time=00:02:01.72 bitrate=6150.5kbits/s speed= 243x
frame=14503 fps=14501 q=-1.0 size=  182016kB time=00:04:01.72 bitrate=6168.4kbits/s speed= 242x
frame=21361 fps=14207 q=-1.0 size=  268032kB time=00:05:56.03 bitrate=6167.2kbits/s speed= 237x
frame=24721 fps=12297 q=-1.0 size=  310272kB time=00:06:52.03 bitrate=6168.8kbits/s speed= 205x
frame=25810 fps=10254 q=-1.0 size=  323840kB time=00:07:10.16 bitrate=6167.2kbits/s speed= 171x
frame=30439 fps=9938 q=-1.0 size=  381696kB time=00:08:27.32 bitrate=6163.4kbits/s speed= 166x
frame=37865 fps=10627 q=-1.0 size=  474880kB time=00:10:31.08 bitrate=6164.4kbits/s speed= 177x
frame=46229 fps=11378 q=-1.0 size=  579840kB time=00:12:50.47 bitrate=6165.1kbits/s speed= 190x
frame=50412 fps=11044 q=-1.0 size=  632320kB time=00:14:00.21 bitrate=6165.1kbits/s speed= 184x
frame=51583 fps=10181 q=-1.0 size=  646656kB time=00:14:19.71 bitrate=6161.8kbits/s speed= 170x
frame=58503 fps=10509 q=-1.0 size=  733440kB time=00:16:15.04 bitrate=6162.1kbits/s speed= 175x
frame=66193 fps=10904 q=-1.0 size=  830208kB time=00:18:23.21 bitrate=6164.8kbits/s speed= 182x
frame=70657 fps=10749 q=-1.0 size=  886016kB time=00:19:37.64 bitrate=6163.4kbits/s speed= 179x
frame=79582 fps=11251 q=-1.0 size=  997888kB time=00:22:06.37 bitrate=6163.2kbits/s speed= 188x
frame=84736 fps=11188 q=-1.0 size= 1062656kB time=00:23:32.26 bitrate=6164.0kbits/s speed= 186x
frame=85672 fps=10609 q=-1.0 size= 1074176kB time=00:23:47.86 bitrate=6162.8kbits/s speed= 177x
frame=93347 fps=10886 q=-1.0 size= 1170432kB time=00:25:55.79 bitrate=6162.9kbits/s speed= 181x
frame=99810 fps=10998 q=-1.0 size= 1251584kB time=00:27:43.48 bitrate=6163.5kbits/s speed= 183x
frame=108711 fps=11353 q=-1.0 size= 1363200kB time=00:30:11.84 bitrate=6163.5kbits/s speed= 189x
frame=113134 fps=11227 q=-1.0 size= 1418496kB time=00:31:25.56 bitrate=6162.8kbits/s speed= 187x
frame=114423 fps=10815 q=-1.0 size= 1434624kB time=00:31:47.05 bitrate=6162.6kbits/s speed= 180x
frame=122317 fps=11040 q=-1.0 size= 1533696kB time=00:33:58.61 bitrate=6163.0kbits/s speed= 184x
frame=127990 fps=11052 q=-1.0 size= 1604864kB time=00:35:33.16 bitrate=6163.2kbits/s speed= 184x
frame=132185 fps=10942 q=-1.0 size= 1657600kB time=00:36:43.09 bitrate=6163.6kbits/s speed= 182x
frame=140290 fps=11150 q=-1.0 size= 1759232kB time=00:38:58.15 bitrate=6163.7kbits/s speed= 186x
frame=145561 fps=11126 q=-1.0 size= 1825536kB time=00:40:26.02 bitrate=6164.3kbits/s speed= 185x
frame=148620 fps=10907 q=-1.0 size= 1863680kB time=00:41:16.99 bitrate=6163.6kbits/s speed= 182x
frame=152045 fps=10760 q=-1.0 size= 1906688kB time=00:42:14.10 bitrate=6163.8kbits/s speed= 179x
frame=159226 fps=10884 q=-1.0 size= 1996544kB time=00:44:13.76 bitrate=6163.2kbits/s speed= 181x
frame=166101 fps=10978 q=-1.0 size= 2082816kB time=00:46:08.34 bitrate=6163.4kbits/s speed= 183x
frame=168570 fps=10785 q=-1.0 size= 2113792kB time=00:46:49.51 bitrate=6163.4kbits/s speed= 180x
frame=169987 fps=10538 q=-1.0 size= 2131456kB time=00:47:13.10 bitrate=6163.2kbits/s speed= 176x
frame=171310 fps=10301 q=-1.0 size= 2148096kB time=00:47:35.16 bitrate=6163.3kbits/s speed= 172x
frame=172704 fps=10080 q=-1.0 size= 2165760kB time=00:47:58.40 bitrate=6163.8kbits/s speed= 168x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\Chris\Downloads\20210424_999189725_Warcraft III.mp4: No space left on device
frame=174002 fps=9906 q=-1.0 Lsize= 2181888kB time=00:48:20.05 bitrate=6163.3kbits/s speed= 165x
video:2125215kB audio:57685kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Chris\AppData\Local\Temp\TL_cc8b220c-7c2e-469e-84f1-61b2978bc0d0'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
>  No space left on device

😄
