### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by oluittv** [Franiac/TwitchLeecher#612]
Hey, thanks for writing this program!

I have had an Issue trying to download a video.
In the middle of the download process, the program stops with this error:

> System.Net.WebException: The remote server returned an error: (403) Forbidden.

Any clues on why the server is rejecting the download?

I use Windows 10 Pro Version 10.0.19042 Build 19042.
More info in the log below:

```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1041843139
Selected Quality: 1600x900@60fps (Source)
Download Url: https://www.twitch.tv/videos/1041843139
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\Videos\RAW\WIP\grand finals round 1\round 1 cut.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\snipe\AppData\Local\Temp\TL_eeea41b9-425e-4bd9-9915-e54b49f6d930

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1622578970%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1041843139%7D
Signature: d2d5561fce89713bb78fc2d90ff0e2320ebba6f1
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\snipe\AppData\Local\Temp\TL_eeea41b9-425e-4bd9-9915-e54b49f6d930'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/index-muted-H0JQND5TUQ.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/720p60/index-muted-H0JQND5TUQ.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/480p30/index-muted-H0JQND5TUQ.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/audio_only/index-muted-H0JQND5TUQ.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/360p30/index-muted-H0JQND5TUQ.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/160p30/index-muted-H0JQND5TUQ.m3u8

Playlist url for selected quality 1600x900@60fps (Source) is https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/index-muted-H0JQND5TUQ.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1037

Starting parallel video chunk download
Number of video chunks to download: 1037
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\snipe\AppData\Local\Temp\TL_eeea41b9-425e-4bd9-9915-e54b49f6d930'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/a1046b60025d404e56af_olui_10463325406_9608210302/chunked/1560-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---
```

Thank you for your time!

**Comment by SuprMaks** [comment]
> This video contains copyright protected music and with that muted parts. Twitch sometimes fails to provide the correct playlist. In other words: Twitch includes files within the playlist that are not on the server or cannot be downloaded (error 403). There is nothing I can do about it. This is Twitch failing not TL.

Is there any chance to skip the failed chunks and process what we have, with some warning alert?
Or, actually I can manually procced the final video by myself, but cant download all this chunks manually. So why is the temp folder cleared in this case? Couse in my particular case, error occurs almost in the end of the record.

**Comment by SuprMaks** [comment]
Sorry and one more question:
I see in my log:

...
Number of video chunks: **2407**
...
Number of video chunks to download: **2407**
...
Downloading file 'https://dgeft87wbj63p.cloudfront.net/da0be3eb64f15a0fb6e4_juice_88920085696_6907639527/chunked/**2418**-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: Удаленный сервер возвратил ошибку: (403) Запрещено.
   в System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   в System.Net.WebClient.DownloadData(Uri address)
   в TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
...

Why is the program trying to overdownload? Cause as I see the failed chunk index is grater than the whole count (2418 > 2407)
