### ISSUE TITLE
Unable to download, Leacher 1.8.4, Win10 64 bit Home Edition. System.Net.WebException: The operation has timed out.

### ISSUE THREAD

**Issue by TAGur1t** [Franiac/TwitchLeecher#613]
hi, have had to recently install windows 10 for my setup, and now am unable to download VODs. As far as I can determine, there have been no changes with my system beyond installing win10 over 8.1. had no issues with running this in 8.1, unsure if theres a security issue (Ive whitelisted the app in all my AV systems for now to try and fix, including malewarebyts and Spybot).

inbound directory has permission and space. 

Twitch link for VOD: https://www.twitch.tv/videos/1045273881

Tried downloading it several different ways, no change in the download errors.

Below is the Error Log

___________________________________________________________________________________________________________________________________
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1045273881
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/1045273881
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Jon\Downloads\20210604_1045273881_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Jon\AppData\Local\Temp\TL_15174ddc-d0b6-4338-82f3-dd0a6fad5f2b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1622914464%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1045273881%7D
Signature: 884efe5c81c89618207a0189345ef0dc521bfa6a
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Jon\AppData\Local\Temp\TL_15174ddc-d0b6-4338-82f3-dd0a6fad5f2b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/720p60/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/720p30/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/480p30/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/audio_only/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/360p30/index-muted-4L34ZLC8JD.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/160p30/index-muted-4L34ZLC8JD.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/index-muted-4L34ZLC8JD.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1463

Starting parallel video chunk download
Number of video chunks to download: 1463
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/324.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/162.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/972.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/812.ts' failed! Trying again in 20s

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1297.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/486.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/648.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1137.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/812.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/162.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/972.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1297.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/726.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/162.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/414.ts' failed! Trying again in 20s

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/972.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1213.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1297.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1213.ts' failed! Trying again in 20s

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/801.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/414.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/801.ts' failed! Trying again in 20s

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/414.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1213.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/801.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Jon\AppData\Local\Temp\TL_15174ddc-d0b6-4338-82f3-dd0a6fad5f2b'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/162.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #2) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/972.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #3) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1297.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #4) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/414.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #5) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/1213.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #6) System.ApplicationException: Could not download file 'https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/801.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by TAGur1t** [comment]
reviewing other issues suggests some sort of instability on my end, which is odd. I'm on a wired hardline with no stability issues that I can see. 

can it be something in win10 network profile I need to look into?

**Comment by Franiac** [comment]
This is not a TL issue. I cannot reproduce any of these errors. The video downloads just fine. Must be an issue with your PC. As you mentioned AV software often blocks unknown web requests and such, especialla if you have cryptic urls like 

`https://d1m7jfoe9zdc1j.cloudfront.net/9ef4bb15f93825f04423_trainwreckstv_42205403421_1622781308/chunked/801.ts`

You talk about "AV systemS"... how many do you have... why?? If you have like 5 AV softwares installed in parallel on Win 10, I am honestly not surprised that nothing works anymore 😅

**Comment by TAGur1t** [comment]
it worked on Win8.1 :(. I'll poke around system see if I can figure out whats blocking it. thanks though
