### ISSUE TITLE
Access to Path is Denied

### ISSUE THREAD

**Issue by Bananasaurus** [Franiac/TwitchLeecher#619]
Hi there. I'm fairly computer illiterate so I apologize in advance if I'm missing information.

- Windows 10 64 bit
- Twitch Leecher version 1.8.4
- Channel: PatrckStatic
- VOD URL: https://www.twitch.tv/videos/1037647581?t=2h32m18s
- Issue: I never specified a temporary download folder and I don't know how to switch it or grant access to it.
- Code:
``Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1037647581
Selected Quality: 852x480@30fps
Download Url: https://www.twitch.tv/videos/1037647581
Crop Start: Yes (02:32:41)
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\jesse\Desktop\Persona 5 PatrckStatic\5-27-2021 Persona 5 PatrckStatic.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\AFedo\AppData\Local\Temp\TL_fff33fcc-418a-414e-81fb-f8fe18c2cd60

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1624639153%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1037647581%7D
Signature: 0765f0902667ad1d4817c7a67943b66048138e87
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\AFedo\AppData\Local\Temp\TL_fff33fcc-418a-414e-81fb-f8fe18c2cd60'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\AFedo\AppData\Local\Temp\TL_fff33fcc-418a-414e-81fb-f8fe18c2cd60'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\AFedo\AppData\Local\Temp\TL_fff33fcc-418a-414e-81fb-f8fe18c2cd60' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\AFedo\AppData\Local\Temp\TL_fff33fcc-418a-414e-81fb-f8fe18c2cd60' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
``

**Comment by Franiac** [comment]
You can set the temporary download path in the preferences. Why you do not have access to your temp path, I cannot tell, unfortunately.

**Comment by Bananasaurus** [comment]
Thank you. I used in administrative mode and it ended up working.
