### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by LavKazan** [Franiac/TwitchLeecher#637]
I am having problems downloading this video. There was a similar issue 2 days ago, but I appear too have plenty of open storage.

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1109643781
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/1109643781
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\20210806_1109643781_Garfield Kart.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\Twitch Temp\TL_d0abbb20-7e31-459c-8c2c-a5c736fc228f

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1629644629%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1109643781%7D
Signature: 5c8848eb02baeb1c9a9aa32bf36375e5b112bdb8
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\Twitch Temp\TL_d0abbb20-7e31-459c-8c2c-a5c736fc228f'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/720p60/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/720p30/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/480p30/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/audio_only/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/360p30/highlight-1109643781.m3u8
https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/160p30/highlight-1109643781.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/highlight-1109643781.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 530

Starting parallel video chunk download
Number of video chunks to download: 530
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'D:\Twitch Temp\TL_d0abbb20-7e31-459c-8c2c-a5c736fc228f'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d2vjef5jvl6bfs.cloudfront.net/8570de97e2bd2a99489f_dondalive_43124332549_3453404613/chunked/777-unmuted.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
Twitch often messes up VOD playlists that contain muted parts. That is not a TL bug. Maybe the VOD was still in processing state when you tried to download it. Nothing I can do here.
