### ISSUE TITLE
Validation for full path length of file (< 250 char) does not check temporary download path

### ISSUE THREAD

**Issue by markni** [Franiac/TwitchLeecher#663]
#451 added a validation to limit downloaded file full path < 250 characters.

However it does not check the full path of temporary download, which is default to `C:\Users\username\AppData\Local\Temp\`

This will break the download under default settings when filename is very long. 

Example error log:

```
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\username\AppData\Local\Temp\TL_2dd96170-a361-443b-8d8b-c129b0a33e86\20211220_1238527711_xQcOW_Just Chatting_OBLIGATORY DEGEN STREAM - NO CHOKE THIS TIME - NO MALD - ONLY JUICE - SKELETON POPS OFF AND TAKES OVER THE WORLD (REAL AND TRUE) AHAHAHAHAHA_000000_000030.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\username\AppData\Local\Temp\TL_2dd96170-a361-443b-8d8b-c129b0a33e86\20211220_1238527711_xQcOW_Just Chatting_OBLIGATORY DEGEN STREAM - NO CHOKE THIS TIME - NO MALD - ONLY JUICE - SKELETON POPS OFF AND TAKES OVER THE WORLD (REAL AND TRUE) AHAHAHAHAHA_000000_000030.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

```
System: Windows 10 Pro 21H1 19043.1415
Video: https://www.twitch.tv/videos/1238527711

**Comment by Franiac** [comment]
problem is, the temporary path ist not constant. the files from the playlist get downloaded into the temp folder with 'tempDir + filename' where the filename gets retrieved from the playlist. This information is not present before the actual download and parsing of the playlist files.

I can assume that a Twitch playlist does not have any files larger than 99999999.ts in them. That would be an assumption. Could fail anyway, but this is the way I am implementing it right now.
