### ISSUE TITLE
Keeps having an error trying to download a specific part of the video?

### ISSUE THREAD

**Issue by MarkusOnRepository** [Franiac/TwitchLeecher#668]
I'm using version 1.8.4. Downloading https://www.twitch.tv/videos/1201578062 .(It will expire today or tomorrow) I'm using Windows 10 64 bit. 

I've been trying to download this video for a few hours now, but I keep getting an error. My only guess is that it can't download a part of the video, but idk why that is.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1201578062
Selected Quality: 284x160@30fps
Download Url: https://www.twitch.tv/videos/1201578062
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: E:\MainFolder\Fionn's Twitch\20211110_Wild Wednesday!_Fionn_theHunter_ Call of the Wild.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Markus\AppData\Local\Temp\TL_58b5f667-01bf-4cb8-b881-1d7d7113e6c6

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1641813974%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1201578062%7D
Signature: 9d87af681b287f5f54a99c2b9c4955de08279c88
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Markus\AppData\Local\Temp\TL_58b5f667-01bf-4cb8-b881-1d7d7113e6c6'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/chunked/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/720p60/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/480p30/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/audio_only/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/360p30/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/index-dvr.m3u8

Playlist url for selected quality 284x160@30fps is https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1351

Starting parallel video chunk download
Number of video chunks to download: 1351
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/615.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/615.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/462.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/462.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/615.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/18.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Markus\AppData\Local\Temp\TL_58b5f667-01bf-4cb8-b881-1d7d7113e6c6'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/137df3996a2fb1a29145_fionn_43766884956_1636568355/160p30/1200.ts' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
That is Twitch servers acting stupid and rejecting the SSL connection. That's not on TL side 😏
