### ISSUE TITLE
Status: Error, cannot download vods

### ISSUE THREAD

**Issue by Food7alk** [Franiac/TwitchLeecher#71]
Hey mate!
Since last week TwitchLeecher fails to download any vods. It downloads up to 90-96% & drops it, throwing an error in the end. I tried grabbing the same vod in different quality than source and they all failed. Also tried grabbing other vods from the same streamer and also gave a go from another streamer and those failed too hinting towards something not being right in the connection between Twitch & TwitchLeecher. Below is a fresh log of a test run;

`VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 100864777
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/squirrel/v/100864777
Crop Start: Yes (00:05:00)
Crop End: Yes (00:06:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\******\Downloads\20161113_test_Euro Truck Simulator 2.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x86.exe
Temporary Download Folder: C:\Users\******\AppData\Local\Temp\TL_88403e0f-387b-4565-935d-321f20ec46df

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A100864777%2C%22expires%22%3A1479286911%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 222f56ad261957b4e690147dc4226d98433f76c5
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\******\AppData\Local\Temp\TL_88403e0f-387b-4565-935d-321f20ec46df'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/chunked/index-dvr.m3u8
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/high/index-dvr.m3u8
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/medium/index-dvr.m3u8
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/low/index-dvr.m3u8
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/mobile/index-dvr.m3u8
https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/audio_only/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps is https://vod122-ttvnw.akamaized.net/v1/AUTH_system/vods_bbf4/squirrel_23654174944_547056824/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 10240

Starting parallel video chunk download
Number of video chunks to download: 31
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\******\AppData\Local\Temp\TL_88403e0f-387b-4565-935d-321f20ec46df'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---`

**Comment by Franiac** [comment]
The web timeout exception point clearly to a very instable connection on your end. A web timeout occures, whenever TL requests something from the Twitch server and does not get a response in time. There will be a new TL version in the next couple of days where TL re-tries to download failing VOD parts 3 times with an additional 20s wait time -> see #68 

The main issue right now is, whenever a single VOD part fails to download because of the tiniest connection error, the whole download fails. That's not good on instable connections. On my end all VODs of Squirrel get downloaded perfectly. I hope, TL 1.3.3 will smoothen this issue a little bit...

**Comment by Food7alk** [comment]
Thank you
I still can't get around why all of a sudden my connection went unstable. I've been using this app for more than 4 months and didn't have this problem earlier.

**Comment by Franiac** [comment]
Well, the actual download process in TL has not changed since the initial version 1.0. But like I said, perhaps 1.3.3 will help you out.
