### ISSUE TITLE
Copy Log to Clipboard Button Didn't Work

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#73]
http://imgur.com/a/qMOdc

**Comment by Franiac** [comment]
Please provide more information including the log file shown in the image. What operation system are we talking about here?

**Comment by Franiac** [comment]
No response, closed

**Comment by dsnvwlmnt** [comment]
Ah sorry. Windows 10 Home, x64. Log file:

System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at TwitchLeecher.Gui.ViewModels.LogViewVM.Copy()

**Comment by Franiac** [comment]
This is an actual bug in the Microsoft .NET Framework. I implemented a workaround.

🎉
