### ISSUE TITLE
I can't download VODs

### ISSUE THREAD

**Issue by MarkusOnRepository** [Franiac/TwitchLeecher#739]
I'm on Windows 10 64 bit on two computers. I'm using Twitch Leecher 2.0.5. I keep trying to download VODs from https://www.twitch.tv/fionn. it keeps giving me errors about being unable to download a cloudfront file about 10-20% in. I've used 360p, 160p, and audio only for both pcs, giving me the same issue every time. Here is the log.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.5

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1261352168
Selected Quality: 160p (284x160)
Download Url: https://www.twitch.tv/videos/1261352168
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\PC\Downloads\20220112_Fionn_1261352168.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\PC\AppData\Local\Temp\9615defe7bf2446e8c6aa5350ee7185a

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1647228014%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1261352168%7D
Signature: 0553ec03d0a3c2523535c6f246398f42a61b1da8
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\PC\AppData\Local\Temp\9615defe7bf2446e8c6aa5350ee7185a'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '720p60' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/720p60/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/index-dvr.m3u8'

Playlist url for selected quality '160p (284x160)' is 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1477

Starting parallel video chunk download
Number of video chunks to download: 1477
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1312.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1312.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/656.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/656.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1312.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/656.ts' failed! Trying again in 20s
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/0.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\PC\AppData\Local\Temp\9615defe7bf2446e8c6aa5350ee7185a'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' after 3 retries!
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' after 3 retries!
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1148.ts' after 3 retries!
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/208bacb9d3b53fd4d8e7_fionn_44361418012_1642010333/160p30/1312.ts' after 3 retries!
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass26_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
That is Twitch not providing the video files in the playlist. Not a TL issue.
