### ISSUE TITLE
Can't search vods by streamer name: Error "The remote server returned an error: (400) Bad Request."

### ISSUE THREAD

**Issue by pavlov2** [Franiac/TwitchLeecher#802]
Windows 11 64 bit, using most recent version of Twitch Leecher.
When I open the program I get an error message.  I can't search for videos by streamer name.  All the streamer names are red in the drop-down list on the search page, using the channel tab.  I can, however, search for videos and download them if using the URLs tab.

When I hover over the channel name from the drop down menu, there is a message, "The specified channel does not exist on Twitch!" 

But these are all channels that exist and were working just fine in Twitch Leecher a few days ago.

I uninstalled and reinstalled.  I logged out and logged in.

Here is the error log:

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.ApiService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.ApiService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.ApiService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.ApiService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by smiddx** [comment]
Same here

**Comment by NicoleKCat** [comment]
See #800 
Twitch API seems to currently be experiencing issues, nothing to do but wait.

**Comment by Item5319** [comment]
Same problem too

**Comment by MPeti1** [comment]
Should be working by now. If still not, restarting TL and retrying a few times should help, but possibly the latter is enough.

**Comment by pavlov2** [comment]
Yep it's working again.  Will try to close issue.
