### ISSUE TITLE
Download error, don't know the cause

### ISSUE THREAD

**Issue by WithFam** [Franiac/TwitchLeecher#83]
TwitchLeecher 1.3.3
https://www.twitch.tv/elspeth/v/114095696
Windows 7 Home Premium SP1 64-bit

It was downloading and had gotten at least to 60% downloaded. When next I checked on it, it had stopped with an error. The log follows:

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 114095696
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/elspeth/v/114095696
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Downloaded1\WhatCD4\Elspeth_20170111a_114095696_Overwatch_PLONKVIEWER. What a neaty device that is..mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\K\AppData\Local\Temp\TL_cb3b0329-368a-45c0-981c-1526b87498e8

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A114095696%2C%22expires%22%3A1484257875%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: f7deee4666703be07785988cdb7d6488f99198de
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\K\AppData\Local\Temp\TL_cb3b0329-368a-45c0-981c-1526b87498e8'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/high/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/medium/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/low/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/mobile/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/audio_only/index-dvr.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2250

Starting parallel video chunk download
Number of video chunks to download: 2250
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=29280436&end_offset=31184123' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=29280436&end_offset=31184123' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=29280436&end_offset=31184123' failed! Trying again in 20s
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\K\AppData\Local\Temp\TL_cb3b0329-368a-45c0-981c-1526b87498e8'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass53_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass53_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=0&end_offset=1948995' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---

---> (Inner Exception #1) System.ApplicationException: Could not download file 'https://vod.edgecast.hls.ttvnw.net/v1/AUTH_system/vods_bcaa/elspeth_24212144992_581929564/chunked/index-0000002189-95cz.ts?start_offset=29280436&end_offset=31184123' after 3 retries!
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass10.<ExecuteSelfReplicating>b__f(Object param0)<---
<---

**Comment by Franiac** [comment]
TL failed to download a part of the VOD. Twitch server returned no data for that specific part of the VOD playlist. Sorry, but there is nothing I can do. If Twitch does not provide the file, I'm not able to download it :(
